### ISSUE TITLE
sqlalchemy "Can't reconnect until invalid "

### ISSUE THREAD

**Issue by AaronVigal** [isislab/CTFd#129] opened 2016-07-18 01:39 UTC
About every 5 minutes or so the whole flask server will go down and it will error out with this: 

>[2016-07-17 20:27:36,118] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/app.py", line 1837, in preprocess_request
    rv = func()
  File "/home/aaron/Desktop/CTFd/CTFd/utils.py", line 108, in needs_setup
    if not is_setup():
  File "/home/aaron/Desktop/CTFd/CTFd/utils.py", line 154, in is_setup
    setup = Config.query.filter_by(key='setup').first()
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: u'SELECT config.id AS config_id, config.`key` AS config_key, config.value AS config_value \nFROM config \nWHERE config.`key` = %s \n LIMIT %s'] [parameters: ('setup', 1)]
Traceback (most recent call last):
  File "serve.py", line 3, in <module>
    app.run(debug=False, host="0.0.0.0", port=4000)
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/home/aaron/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/home/aaron/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/home/aaron/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/aaron/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/aaron/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/home/aaron/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/aaron/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/app.py", line 1574, in handle_exception
    return handler(e)
  File "/home/aaron/Desktop/CTFd/CTFd/utils.py", line 81, in general_error
    return render_template('errors/500.html'), 500
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/aaron/.local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/aaron/.local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aaron/Desktop/CTFd/CTFd/templates/errors/500.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aaron/Desktop/CTFd/CTFd/templates/base.html", line 4, in top-level template code
    <title>{{ ctf_name() }}</title>
  File "/home/aaron/Desktop/CTFd/CTFd/utils.py", line 134, in ctf_name
    name = get_config('ctf_name')
  File "/home/aaron/Desktop/CTFd/CTFd/utils.py", line 279, in get_config
    config = Config.query.filter_by(key=key).first()
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/home/aaron/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'SELECT config.id AS config_id, config.`key` AS config_key, config.value AS config_value \nFROM config \nWHERE config.`key` = %s \n LIMIT %s'] [parameters: [immutabledict({})]]

The only thing I have changed is the database to MySQL. The only changed line in the new CTFd/config.py looks like this: 
`SQLALCHEMY_DATABASE_URI = 'mysql+mysqldb://<db name>:<Password>@<ip addr>/<db table>
`
What is the issue? Any help is much appreciated. Thank you!

**Comment by ColdHeat** [comment] 2016-07-18 01:41
This stack trace is impossible to read but I have a feeling I've heard about this issue before. Can you try using the custom_themes branch?

**Comment by AaronVigal** [comment] 2016-07-18 01:42
Sure. Thank you for replying so quickly!

**Comment by ColdHeat** [comment] 2016-07-18 15:51
Hey @AaronVigal does this still happen for you?

**Comment by AaronVigal** [comment] 2016-07-18 19:12
It does. I can't figure out what the issue is. I think the stack trace is a
little different this time. This is what it looks like:
<code>
Traceback (most recent call last):
  File "serve.py", line 3, in <module>
    app.run(debug=False, host="0.0.0.0", port=4000)
  File "/home/aaron/.local/lib/python2.7/site-packages/flask/app.py", line
843, in run
    run_simple(host, port, self, **options)
  File
"/home/aaron/.local/lib/python2.7/site-packages/werkzeug/serving.py", line
694, in run_simple
    inner()
  File
"/home/aaron/.local/lib/python2.7/site-packages/werkzeug/serving.py", line
659, in inner
    srv.serve_forever()
  File
"/home/aaron/.local/lib/python2.7/site-packages/werkzeug/serving.py", line
499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 292, in
_handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 290, in
_handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe
</code>

**Comment by ColdHeat** [comment] 2016-07-18 19:15
I think that is a different error related to the browser closing the connection before the server is finished. I don't believe that crashes the entire server though.

**Comment by AaronVigal** [comment] 2016-07-18 20:26
It ends the python serve.py proccess which takes down the whole server. I
have tried it in multiple browsers and different computers and it does the
same thing. Also, how can I go about deploying this on a live website? I am
using GoDaddy to host it. How can I do this? I have never used Python for a
backend

**Comment by ColdHeat** [comment] 2016-07-18 20:30
You'll need to follow some of the documentation here: https://github.com/isislab/CTFd/wiki/Deployment

I am not sure if GoDaddy gives you the control you need to be able to setup CTFd but so long as you can run some commands through SSH you'll be able to set it up. 

What steps are you taking to reproduce this error across multiple browsers?

**Comment by AaronVigal** [comment] 2016-07-18 20:36
There's no consistency to when it happens it is completely random which
makes it really hard to fix

**Comment by ColdHeat** [comment] 2016-07-18 20:38
I believe that's a browser issue that goes away when you use a better server for deployment like gunicorn or uwsgi.

**Comment by AaronVigal** [comment] 2016-07-18 20:43
Alright. That makes sense since it was deployed on an Ubuntu Virtual
Machine. Thank you for all of your help!

**Comment by ColdHeat** [comment] 2016-07-19 02:27
I think your other issue is due to the Flask development server buffering the output of the graphs page. When you browse to the config page, this aborts the graph request and Flask ends up sending data to an aborted connection. 

Will look into a fix.

**Comment by ColdHeat** [comment] 2016-07-29 17:00
This should be fixed here: afbd4b5f8a30729068567c956dedebdc4224dd04

**Closed by ColdHeat** 2016-07-29 17:00 UTC
