### ISSUE TITLE
config page not updating

### ISSUE THREAD

**Issue by edenecho** [isislab/CTFd#146] opened 2016-08-31 07:28 UTC
I have installed CTFd on Ubuntu 16.04, hosted using Flask and Postgresql. Everything runs well except the config page could not be configured once updated. Every options in the config page are ticked and could not be unticked.

**Comment by ColdHeat** [comment] 2016-09-03 18:38
Can you try updating your instance? I believe this is fixed in master and I cannot reproduce.

**Closed by ColdHeat** 2016-09-03 18:38 UTC
