### ISSUE TITLE
Unable to edit challenges properly

### ISSUE THREAD

**Issue by jacobj10** [isislab/CTFd#94] opened 2016-02-18 15:49 UTC
Challenges tab in admin panel comes up as blank, not showing any of the already created challenges making it impossible to edit/remove them.

**Comment by ColdHeat** [comment] 2016-02-18 15:52
I'm unable to replicate. Can you give me a stack trace or an error from Chrome Inspector?

**Comment by Drybones3363** [comment] 2016-02-18 17:59
![image](https://cloud.githubusercontent.com/assets/15837070/13152901/6cff9aba-d63f-11e5-9384-6ecd9d6626d8.png)

**Comment by ColdHeat** [comment] 2016-02-18 18:32
![screen shot 2016-02-18 at 1 31 23 pm](https://cloud.githubusercontent.com/assets/166333/13153835/efa80ef8-d643-11e5-8fdf-2b4956890616.png)

Sorry, I'm still unable to reproduce. I can look deeper later.

**Comment by ColdHeat** [comment] 2016-04-20 18:25
Considering this closed as there hasn't been much response and I'm able to edit challenges on Chrome.

**Closed by ColdHeat** 2016-04-20 18:25 UTC
